name: CI

# Run on push with specific tag
on:
  push:
    tags:
      - experiment*

jobs:
  dockerbuild:
    name: Docker Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # XXX: run script and double check optimizations
        opt_flag: [O0,O1,O2,O3,Oz,correlated-propagation,early-cse,early-cse-memssa,functionattrs,globalopt,gvn,inferattrs,instcombine,jump-threading,licm,loop-rotate,mem2reg,reassociate,simplifycfg,sroa,]
        # To avoid timeouts, split to 4 batches with 25 experiments each
        batch: [0, 1, 2, 3,]
        inputs: [100, 200,]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Run docker build
        run: docker build -t opt_analysis:latest .
      - name: Run experiment
        run: docker run -e "OPT_TO_USE=${{ matrix.opt_flag }}" -e "OPT_BATCH=${{ matrix.batch }}" -e "OPT_RUNS=${{ matrix.inputs }}" -v "$PWD:/workspace" --workdir /workspace opt_analysis:latest scripts/nsc2013.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: results
          path: results
