name: CI

# Run on push with specific tag
on:
  push:
    tags:
      - experiment*

jobs:
  dockerbuild:
    name: Docker Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        # XXX: run script and double check optimizations
        opt_flag: [1,2,3,4,5,6,7,8,9]
        # To avoid timeouts, split to 4 batches with 25 experiments each
        batch: [0, 1, 2, 3]
        target: [nsc2013,]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Run docker build
        run: docker build -t opt_analysis:latest .
      - name: Run experiment
        run: docker run -e "OPT_TO_USE=${{ matrix.opt_flag }}" -e "OPT_BATCH=${{ matrix.batch }}" -e "OPT_RUNS=200" -v "$PWD:/workspace" --workdir /workspace opt_analysis:latest scripts/${{ matrix.target }}.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: results
          path: results
